[Rule]
#TITLE=trade
#VER=202606008
DOMAIN-SUFFIX,wbrks.com,PROXY
DOMAIN-SUFFIX,lbkrs.com,PROXY
DOMAIN-SUFFIX,longbridge.com,PROXY
DOMAIN-SUFFIX,longbridge.cn,PROXY
DOMAIN-SUFFIX,longbridge.hk,PROXY
DOMAIN-SUFFIX,longportapp.cn,PROXY
DOMAIN-SUFFIX,longportapp.com,PROXY

