[Rule]
#TITLE=trade
#VER=202606008
DOMAIN-SUFFIX,wbrks.com
DOMAIN-SUFFIX,lbkrs.com
DOMAIN-SUFFIX,longbridge.com
DOMAIN-SUFFIX,longbridge.cn
DOMAIN-SUFFIX,longbridge.hk
DOMAIN-SUFFIX,longportapp.cn
DOMAIN-SUFFIX,longportapp.com

